### ISSUE TITLE
ur dum lol

### ISSUE THREAD

**Issue by dd86k** [Chaquator/turbo-meme-generator#1]
# dude there are no output samples like dude i wanna see an example!!!!!! pls screenshot something!!!!!!!!!!!!!!!!!!

**Comment by chaquator** [comment]
oh ye good point one sec

edit: `𝔽𝕠𝕜𝕚𝕟 𝕕𝕦𝕟`

**Comment by dd86k** [comment]
oh shit man the world will praise you (especially **9gag**)

**Comment by dd86k** [comment]
happy birhdtyday!!!!!!
